#!/bin/bash

profile=""

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

remove=false

for var in "$@"
do
    if [ $var == "--remove" ]
    then
        remove=true
    fi
done

if [ -z "$1" ] || [ "$1" == "--remove" ]
then
    profile=$(ls ~/.axiom/profiles | cat | fzf)
else
    exists=$(ls ~/.axiom/profiles | cat | grep "\<$1\>" | wc -l | awk '{ print $1 }')
    if [ "$exists" == "1" ]
    then
        profile="$1"
    else
        echo "Profile doesnt exist, launching selector..."
        profile=$(ls ~/.axiom/profiles | cat | fzf)
    fi
fi

success_command=$(cat ~/.axiom/profiles/$profile/manifest.json | jq -r '.success_message')
id="$RANDOM"
filename="/tmp/$id.sh"

if [ $remove == false ]
then
	cat ~/.axiom/profiles/$profile/manifest.json | jq -r '.commands[]' > $filename
elif [ $remove == true ]
	then
	cat ~/.axiom/profiles/$profile/manifest.json | jq -r '.remove_commands[]' > $filename
fi
chmod +x $filename

if [ $remove == false ]
then
	echo -e "${BWhite}Installing profile '$profile'...${Color_Off}"
elif [ $remove == true ]
	then
	echo -e "${BWhite}Uninstalling profile '$profile'...${Color_Off}"
fi

echo -e "${BBlue}Deployment Output: ${Blue}"
$filename
echo -e "${Green}"
if [ $remove == false ]
then
    echo ""
else 
	echo "Profile succesfully removed!"
fi
echo -n -e "${Color_Off}"
